import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import AboutTwo from '../components/AboutTwo'
import Banner from '../components/Banner'
import Blogs from '../components/Blogs'
import Features from '../components/Features'
import Slider from '../components/slider'
import TimeTable from '../components/TimeTable'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fitness</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Banner />
            <Features />
          <About/>
            <TimeTable/>


            <Slider/>
            <AboutTwo/>
            <Blogs/>
      </main>


    </div>
  )
}
